### ISSUE TITLE
LFortran Runtime Library not available

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lfortran/lcompilers_frontend#10]
code:
```fortran
program expr2
    implicit none

    integer :: x

    x = -2
    print *, abs(x)

end program
```
output:
```bash
semantic error: Module 'lfortran_intrinsic_math' not declared in the current source and the modfile was not found
 --> input:7:14
  |
7 |     print *, abs(x)
  |              ^^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

**Comment by certik** [comment]
Yes, we don't have these accessible in WASM. One option is to somehow pack these into the WASM binary; for example what if we somehow pack all these files and include them directly in C++ code, then we access them as compile time constants, or something like that.

**Comment by Shaikh-Ubaid** [comment]
The `pure` part of the runtime library is available at https://dev.lfortran.org. The example shared in https://github.com/lfortran/lcompilers_frontend/issues/10#issue-1335002265 works.

We need to get the impure part working. I guess we have a dedicated issue for it here https://github.com/lcompilers/lpython/issues/1413.

Dr. Ondrej, is this issue safe to close?

**Comment by certik** [comment]
Yes, I think we can close it.
