### ISSUE TITLE
When loading a gist, do not show "mandelbrot.f90"

### ISSUE THREAD

**Issue by certik** [lfortran/lcompilers_frontend#103]
The name of the file should not be "mandelbrot.f90" when loading from gist.

**Comment by Shaikh-Ubaid** [comment]
In https://github.com/lfortran/lcompilers_frontend/pull/105,

By default whether loading from gist or not, we just name it `main.f90`. I think this is helpful as one can simply start editing in it and the name `main.f90` seems to be in sync.

If `gist` or `code` are not provided, then the `main.f90` contains `mandelbrot` source code.

**Comment by certik** [comment]
Yes, that's fine. Thanks!
