### ISSUE TITLE
Do not include `lfortran.wasm` in this repo

### ISSUE THREAD

**Issue by certik** [lfortran/lcompilers_frontend#12]
Right now, the `lfortran.wasm` is included in the repo: https://github.com/lfortran/lcompilers_frontend/blob/master/public/lfortran.wasm, but that will not scale as we start updating it on every LFortran commit, since it is 2.5MB each.

So we either need to build it automatically from the latest LFortran commit, or we need to download a prebuilt version from somewhere. Probably the latter option: LFortran's CI will build the wasm file, and push somewhere. Then this repository will download it. That way we know exactly what file is being used and can easily debug by hand if needed.

**Comment by Shaikh-Ubaid** [comment]
>that will not scale as we start updating it on every LFortran commit, since it is 2.5MB each.

**doubst:** 
- Since the `lfortran.wasm` is of size around `2.5 MB` (which seems to be (possibly) a constant or might increase slightly with more updates), please could someone possibly share/clarify how the current approach (of `lfortran.wasm` in `master`) might/would not scale?
- Also, please, could someone possibly clarify what do we mean by `scale` here?

**Comment by certik** [comment]
After discussing this, we decided to create https://github.com/lfortran/wasm_builds which should receive the automatic commits of `lfortran.wasm` (just like the `tarballs` repo). Then in this repo (https://github.com/lfortran/lcompilers_frontend) we should just download it at the CI, after triggering the CI with a webhook.

**Comment by Shaikh-Ubaid** [comment]
**Update:** With https://github.com/lfortran/lcompilers_frontend/pull/35, we are not including the `lfortran.wasm` and `lfortran.js` in this repository (and thus, they are also added to `.gitignore`). We currently download the `lfortran.wasm` and `lfortran.js` from https://github.com/lfortran/wasm_builds for a given specific commit of `lfortran`. As per discussion in https://github.com/lfortran/lcompilers_frontend/issues/31, we are hoping to manually update/increment the `commit` Id/SHA to be used for fetching/downloading `lfortran.wasm` and `lfortran.js` from `wasm_builds`.

**Comment by Shaikh-Ubaid** [comment]
Please, could someone possibly share if this issue is safe to close?

**Comment by certik** [comment]
I think this is fixed, thanks!
