### ISSUE TITLE
Run the CI for all pull requests, ensuring the page can build

### ISSUE THREAD

**Issue by certik** [lfortran/lcompilers_frontend#15]
Currently the CI only runs master to deploy it, but we need to run the same commands on every pull request (except the final deploy) in order to ensure that we do not accidentally break anything.

**Comment by certik** [comment]
This is probably the highest priority now. Once we have this, it would prevent what happened in https://github.com/lfortran/lcompilers_frontend/issues/32.

We need to run through the whole build, download the correct lfortran, build everything. Except the final push: in fact we should push into some temporary repository into some branch, that we can then view online to check if everything works as expected and to test some changes *before* we merge.

**Comment by Shaikh-Ubaid** [comment]
I would like to work on this. Please, could someone possibly share if we might need an extra repository where we could deploy `PRs`?

**Comment by certik** [comment]
I think we would. Just set it up in your own temporary repository, once it works, we can move it to lfortran.

**Comment by Shaikh-Ubaid** [comment]
>Just set it up in your own temporary repository, once it works, we can move it to lfortran.

Got it. Thank you.

**Comment by Shaikh-Ubaid** [comment]
Please, could someone possibly share if this issue is fixed? 

Also, currently the CI pushes the development deployment to https://github.com/lfortran/pull_request_preview and each push overrides the previous development deployment. I guess, we can fix this later as the project matures?

**Comment by certik** [comment]
Yes, I think that's fine.

It looks like it is working, thanks for fixing i!
