### ISSUE TITLE
Improve the layout on a phone

### ISSUE THREAD

**Issue by certik** [lfortran/lcompilers_frontend#28]
On my iPhone, the site works, but I can only see the code window, I have to scroll down to see the output. So people might not realize there is an image output.

**Comment by Shaikh-Ubaid** [comment]
https://github.com/lfortran/lcompilers_frontend/blob/4bea658bb41da37c85ae635fee28512809114638/pages/index.js#L59-L67

It seems we might need a `useEffect()` to accomplish this. We previous had this `useEffect` as shown above.

Also, I came across this https://stackoverflow.com/questions/59494037/how-to-detect-the-device-on-react-ssr-app-with-next-js. It seems useful.

**Comment by certik** [comment]
This is how it looks like on my iPhone now:

![IMG_3411](https://user-images.githubusercontent.com/20568/214695454-b16dae7c-c19d-42c4-9516-dc64bfe9eebc.PNG)

So I think the issue is fixed. Thanks a lot @Shaikh-Ubaid for fixing it!
