### ISSUE TITLE
Urgent: Latest LFortran update broke all compilation

### ISSUE THREAD

**Issue by certik** [lfortran/lcompilers_frontend#50]
Here is how it currently looks like:

<img width="1678" alt="Screen Shot 2022-11-22 at 7 44 03 PM" src="https://user-images.githubusercontent.com/20568/203454435-add50671-fb79-4d88-a03a-4c9004ccb6e1.png">

This happened after I merged https://github.com/lfortran/lcompilers_frontend/pull/49. The preview looked ok, but all the template stuff (as implemented in https://github.com/lfortran/lfortran/pull/1021) also didn't work, but at least Mandelbrot worked. It almost looked like if LFortran didn't properly updated in the preview.

For now I tried to fix this by reverting the latest deploy in: https://github.com/lfortran/lcompilers_frontend/commit/fe6038d1d7d6ff2d1ab899d3e22e7fe8d9e1333b.

But it still didn't fix it for me. I have no idea why.

@Shaikh-Ubaid do you think you could please investigate? I have no idea what is going on. Reverting the gh-pages should fix it, but it didn't.

**Comment by certik** [comment]
I tested in a private browser window and it seems it works again. Perhaps it only broke temporarily after all.

@Shaikh-Ubaid can you test it and see if it works for you?

If so, then it's not urgent. Something still broke and we'll have to investigate, but it's not urgent.

**Comment by Shaikh-Ubaid** [comment]
I think I figured the solution. Fix incoming.

**Comment by Shaikh-Ubaid** [comment]
>This happened after I merged https://github.com/lfortran/lcompilers_frontend/pull/49. The preview looked ok, but all the template stuff (as implemented in https://github.com/lfortran/lfortran/pull/1021) also didn't work, but at least Mandelbrot worked. It almost looked like if LFortran didn't properly updated in the preview.

I shared about it here https://github.com/lfortran/lcompilers_frontend/pull/49#issuecomment-1324718179

**Comment by Shaikh-Ubaid** [comment]
We are unable to update the commit at the moment. The repository https://github.com/lfortran/wasm_builds is not building. Thus the `lfortran.js/wasm/data` files are not available to be downloaded by the `build.sh` script.

Upcoming Steps:
- Fix `wasm_builds` repository building
- Update lfortran commit
