### ISSUE TITLE
Add a link to this repository

### ISSUE THREAD

**Issue by certik** [lfortran/lcompilers_frontend#6]
The website should link this repository (https://github.com/lfortran/lcompilers_frontend), and possibly we should just invite people to report issues with it at https://github.com/lfortran/lcompilers_frontend/issues.

**Comment by BhaswatiRoy** [comment]
Hello 
After going through the website https://dev.lfortran.org/
I believe the link to the GitHub repo and issues section can be added in the footer section of the landing page 
![image](https://user-images.githubusercontent.com/78029145/212458605-c14ae222-8513-49ee-ad61-640bc7e108c9.png)
I can work on this issue

**Comment by certik** [comment]
@BhaswatiRoy yes, go ahead and work on it!

**Comment by BhaswatiRoy** [comment]
Hello @certik 
I have submitted the pr
