### ISSUE TITLE
Add detailed instructions into README how to set it up locally

### ISSUE THREAD

**Issue by certik** [lfortran/lcompilers_frontend#7]
Ideally using Conda. I'll try to set it up and update the instructions eventually.

**Comment by Shaikh-Ubaid** [comment]
Is this issue safe to close? We have instructions in the README that help to set up the project locally.

The instructions are not best yet. We rely on (a small hack) `MY_ENV=production`, which we will fix soon. Dr. Ondrej, please share if fixing it is a priority.

**Comment by certik** [comment]
Yes, this is fixed, thanks!
