### ISSUE TITLE
Add links to source code and issues in Footer

### ISSUE THREAD

**Issue by suhanigarg29** [lfortran/lcompilers_frontend#76]

**Comment by Shaikh-Ubaid** [comment]
I think we added links to lfortran repository and issues page in https://github.com/lfortran/lcompilers_frontend/pull/56. 

The same can be seen at https://dev.lfortran.org.
<img width="484" alt="Screenshot 2023-04-01 at 10 49 29 PM" src="https://user-images.githubusercontent.com/43722035/229305385-c1ef70a4-d701-42ad-91ac-bec0fd23ad79.png">

**Comment by suhanigarg29** [comment]
They aren't present in https://www.ubaidshaikh.me/lcompilers_web_frontend/lpython
Are these 2 websites combined or function separately?

**Comment by Shaikh-Ubaid** [comment]
>They aren't present in https://www.ubaidshaikh.me/lcompilers_web_frontend/lpython

It is not a big issue. We can add/update it anytime. 

I would suggest to consider https://dev.lfortran.org/ as the primary site at present. The features we implement here (https://dev.lfortran.org/) can be easily propagated to https://www.ubaidshaikh.me/lcompilers_web_frontend/lpython.

**Comment by Shaikh-Ubaid** [comment]
>Are these 2 websites combined or function separately?

Could you elaborate your query, please? Their code (and working) structure is similar. They are currently served via separate repositories (We would later hopefully be having single repository/website/url for both).

**Comment by suhanigarg29** [comment]
I was just confused why there were two separate repositories for the same purpose

**Comment by certik** [comment]
@suhanigarg29 yes, I would like to merge both efforts, but we didn't have time. I just created an issue for it: https://github.com/lfortran/lcompilers_frontend/issues/77

**Comment by suhanigarg29** [comment]
@certik Can you please explain where I'll have to submit my GSoC proposal (LPython or LFortran)? Since this repo is listed under LPython projects, but if it gets merged with LFortran, will there be a distinction?

**Comment by certik** [comment]
Submit LPython proposal to PSF and LFortran to fortran-lang orgs.

**Comment by suhanigarg29** [comment]
This project is for LPython, right?

**Comment by certik** [comment]
This project can be both, so apply to both.

**Comment by suhanigarg29** [comment]
Thank You sir!
