### ISSUE TITLE
Google Analytics Issues

### ISSUE THREAD

**Issue by HaoZeke** [lfortran/lcompilers_frontend#93]
TL;DR we should switch [to GoatCounter](https://github.com/arp242/goatcounter):

https://www.goatcounter.com/

This doesn't need GDPR and they're quite good
https://www.goatcounter.com/help/gdpr
https://www.goatcounter.com/help/privacy

Longer answer:
https://github.com/lfortran/lcompilers_frontend/pull/92 introduced analytics, which means we now need to let the users know (banners are typical) or not use GA.

References:
https://matomo.org/blog/2022/05/google-analytics-4-gdpr/
![image](https://github.com/lfortran/lcompilers_frontend/assets/4336207/1661238c-81e1-45b9-8cbe-6aa6c43577a2)

**Comment by HaoZeke** [comment]
cc @certik @Shaikh-Ubaid

**Comment by certik** [comment]
Yes, let's switch it to it.
